services:
  sportgearhbu-web-provider:
    container_name: sportgearhbu-web-provider
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "${WEB_PROVIDER_HTTP_PORT:-8080}:3000"
