services:
  sportgearhub-web-provider:
    container_name: sportgearhub-web-provider
    image: "${WEB_PROVIDER_IMAGE:-ghcr.io/sportgearhub/sportgearhub-web-provider:production}"
    restart: unless-stopped
    ports:
      - "${WEB_PROVIDER_HTTP_PORT:-8080}:80"
    networks:
      apps-proxy:
        aliases:
          - sportgearhub-web-provider

networks:
  apps-proxy:
    external: true
